services:
  airport:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
      - my_media:/files/media
      - my_static:/files/static
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
    - db
    healthcheck:
      test: curl --fail http://localhost:8000/ || exit 1
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 60s

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
    - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:
  my_media:
  my_static: