# Generated by Django 5.2 on 2025-05-11 13:50

import airport_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport_app.models.airplane_image_path
            ),
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_city_per_country"
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("name", "code"), name="unique_country_name_code"
            ),
        ),
    ]
